on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    uses: './.github/workflows/build.yml'
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./build
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/*
permissions:
  contents: write